name: run-tests-when-push-or-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Build Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test
